---
# Intall spf13 in any debian systems
- name: Copy iptables rules
  copy: src={{ webserver_common_iptables_file }} dest=./

- name: Apply iptables rules
  shell: iptables-restore < rules.iptables
  sudo: yes
