---
# Intall spf13 in any debian systems
- name: Install zsh package
  apt: name=zsh state=latest update_cache=yes
  sudo: yes

- name: Checkout github repo
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: Backuo zshrc
  copy: src=.zshrc dest=~/.zshrc backup=yes

- name: Change user shell
  user: name=vagrant shell=/bin/zsh
  sudo: yes
